config/routes.rb
Rails.application.routes.draw do
  root'people#index'

  resources :people

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :avatar, :phone, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: @person, class: 'ui form') do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, required: true %>
  <br />
  <%= f.label :last_name %>
  <%= f.text_field :last_name, required: true %>
  <br />
  <%= f.lable :avatar %>
  <%= f.text_field :avatar %>
  <br />
  <%= f.lable :email %>
  <%= f.text_field :email %>
  <br />
  <%= f.lable :phone %>
  <%= f.text_field :phone %>
  <br />
  <%= f.submit nil, class: 'ui button primary' %>

  <% end %>
  
  
  

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1 class="ui header">People<h1>
<%= link_to 'New Person', new_person_path %>
<div class="ui divider"></div>

<div class="ui grid">
  <% @people.each do |person| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
     <div class="ui card">
      <div class="image">
        <img src="htpp://robohash.org/<%= person.avatar %>?set=3" />
        </div>
        <div class="extra content">
          <div class ="ui two buttons">
            <div class="basic green button">
              <%= link_to 'Edit', edit_person_path(person.id) %>
            </div>
            <div class="basic red button">
            <%= link_to 'Delete', person_path(person.id), method: :delete, data: {confirm: 'Are you sure?'}%>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @person.avatar %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @person.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>